name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout zh-hans.react.dev code
        uses: actions/checkout@v4
        with:
          repository: reactjs/zh-hans.react.dev

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 'config'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: ls -al
        working-directory: config
      - run: node config/scripts.mjs
      - run: ls -al

      - run: cp config/Dockerfile ./

      - name: Create dockerignore file.
        run: |
          cat > .dockerignore << EOF
          Dockerfile
          .dockerignore
          config
          node_modules
          npm-debug.log
          README.md
          .next
          .git
          EOF
 
      - run: ls -al
    
      # Create Docker Image
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image:latest
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          tags: ${{ secrets.DOCKER_USER }}/zh-hans.react.dev:latest
