name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout zh-hans.react.dev code
        uses: actions/checkout@v2
        with:
          repository: reactjs/zh-hans.react.dev
          path: 'app'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install
        working-directory: app

      - name: Build Next.js app
        run: npm run build
        working-directory: app

      - run: ls -al
      - run: cp Dockerfile ./app
    
      # Create Docker Image
      - uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image:latest
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./app/
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USER }}/zh-hans.react.dev:latest
